-- Create health_tips table
CREATE TABLE IF NOT EXISTS public.health_tips (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'Geral',
    icon_type TEXT DEFAULT 'Lightbulb',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.health_tips ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read tips
CREATE POLICY "Allow authenticated read health_tips" 
ON public.health_tips FOR SELECT 
TO authenticated 
USING (true);

-- Populate with initial tips (Batch 1: 100 Tips)
INSERT INTO public.health_tips (title, content, category, icon_type) VALUES
('Mantenha-se Hidratado', 'Beber água regularmente ajuda na absorção de muitos medicamentos e mantém seus rins saudáveis.', 'Saúde', 'Droplet'),
('Organização e Segurança', 'Mantenha seus medicamentos nas embalagens originais para evitar confusões de dosagem.', 'Segurança', 'Shield'),
('Armazenamento Correto', 'Evite guardar remédios no banheiro. A umidade pode comprometer a eficácia das fórmulas.', 'Dicas', 'Home'),
('Apoio Familiar', 'Compartilhar seu histórico com um cuidador traz mais segurança para o seu tratamento diário.', 'Família', 'Users'),
('Sol e Medicamentos', 'Alguns remédios aumentam a sensibilidade da pele ao sol. Use protetor solar sempre!', 'Cuidado', 'Sun'),
('Check-up Regular', 'Anote suas dúvidas para a próxima consulta médica direto no Diário de Saúde.', 'Prevenção', 'Clipboard'),
('Horário do Sono', 'Tome medicamentos indutores de sono sempre no mesmo horário para regular seu ritmo biológico.', 'Sono', 'Moon'),
('Alimentação e Remédios', 'Siga as orientações sobre tomar remédios com ou sem alimentos. Isso faz diferença na absorção.', 'Dicas', 'Apple'),
('Atividade Física Leve', 'Uma caminhada de 15 minutos melhora a circulação e ajuda no bem-estar mental.', 'Bem-estar', 'Activity'),
('Data de Validade', 'Faça uma revisão mensal na sua caixa de remédios e descarte o que estiver vencido corretamente.', 'Manutenção', 'Calendar'),
('Cuidado com a Automedicação', 'Mesmo remédios naturais podem interagir com seu tratamento. Sempre informe seu médico.', 'Atenção', 'AlertTriangle'),
('Postura ao Tomar Pílulas', 'Tomar comprimidos sentado ou em pé facilita a passagem pelo esôfago.', 'Dicas', 'User'),
('Luz Natural', 'Tente se expor à luz do sol pela manhã para ajudar a regular o humor e a vitamina D.', 'Bem-estar', 'Sun'),
('Dose em Dobro?', 'Nunca tome uma dose em dobro se esqueceu a anterior. Siga o horário seguinte ou fale com o médico.', 'Urgência', 'Zap'),
('Higiene das Mãos', 'Lave sempre as mãos antes de manusear seus medicamentos para evitar contaminações.', 'Higiene', 'Info'),
('Frutas Cítricas', 'Sabia que o suco de toronja (grapefruit) pode interagir negativamente com vários remédios?', 'Curiosidade', 'Fruit'),
('Anotações de Sintomas', 'Sentiu algo diferente? Use o Diário de Sintomas para não esquecer de contar ao médico.', 'Monitoramento', 'Edit3'),
('Descarte Consciente', 'Não jogue remédios no lixo comum ou no vaso. Procure pontos de coleta em farmácias.', 'Planeta', 'Trash2'),
('Importância do CAFÉ', 'O consumo excessivo de café pode interferir na absorção de remédios para tireoide e pressão.', 'Nutrição', 'Coffee'),
('Ria Mais!', 'O riso libera endorfinas que ajudam a reduzir a dor e melhorar a imunidade corporal.', 'Humor', 'Smile'),
('Cuidado com o Sal', 'Reduzir o sal na comida ajuda a controlar a pressão arterial e diminui o inchaço nas pernas.', 'Nutrição', 'Droplet'),
('Caminhada Segura', 'Ao sair para caminhar, use calçados confortáveis e fechados para evitar quedas e ferimentos.', 'Segurança', 'Activity'),
('Organização Visual', 'Use etiquetas coloridas para identificar remédios de uso contínuo vs uso esporádico.', 'Organização', 'Edit3'),
('Ouvir o Próprio Corpo', 'Fique atento a efeitos colaterais novos e anote o horário em que aparecem.', 'Monitoramento', 'Heart'),
('Socialização é Saúde', 'Conversar com amigos ou familiares via vídeo ou pessoalmente faz bem para o coração e a mente.', 'Bem-estar', 'Users'),
('Evite Escadas Escuras', 'Mantenha os caminhos da casa bem iluminados para evitar acidentes durante a noite.', 'Segurança', 'Sun'),
('Importância do Peixe', 'Consumir peixes grelhados como sardinha e atum ajuda a manter a mente afiada (Ômega-3).', 'Nutrição', 'Apple'),
('Não Moer Comprimidos', 'Nunca amasse comprimidos sem orientação. Alguns têm revestimento para liberação lenta.', 'Importante', 'AlertTriangle'),
('Visão em Dia', 'Consulte o oftalmologista anualmente. Enxergar bem é essencial para ler as bulas corretamente.', 'Prevenção', 'Clipboard'),
('Plantas em Casa', 'Cuidar de plantas pode ser uma terapia relaxante e ajuda a reduzir o estresse diário.', 'Terapia', 'Smile'),
('Beber Água ao Acordar', 'Um copo de água ao acordar desperta o sistema digestivo e hidrata após o sono.', 'Hábito', 'Droplet'),
('Postura na Leitura', 'Ao ler no celular ou livros, mantenha-os na altura dos olhos para não forçar o pescoço.', 'Ergonomia', 'User'),
('Chás Calmantes', 'Camomila e erva-cidreira são ótimos antes de dormir, mas verifique se não interagem com seus remédios.', 'Sono', 'Moon'),
('Cuidado com Tapetes', 'Tapetes soltos são vilões das quedas. Prefira pisos antiderrapantes ou use fitas fixadoras.', 'Segurança', 'Shield'),
('Vitamina D Natural', '15 minutos de sol nos braços e pernas ajudam na fixação do cálcio nos ossos.', 'Saúde', 'Sun'),
('Anotar é Lembrar', 'Sempre que tiver uma dúvida de saúde, anote no Diário aqui do app para não esquecer.', 'Méodo', 'Edit3'),
('Prevenção de Inchaço', 'Evite ficar muito tempo na mesma posição. Movimente os pés mesmo sentado.', 'Circulação', 'Activity'),
('Leitura de Bulas', 'Se a letra da bula estiver pequena, use a função de lupa do celular ou peça ajuda ao cuidador.', 'Dicas', 'Info'),
('Equilíbrio Mental', 'Pratique a gratidão diariamente. Pensamentos positivos fortalecem o sistema imunológico.', 'Mente', 'Heart'),
('Vacinação em Dia', 'Mantenha sua carteira de vacinação atualizada, especialmente para Gripe e Pneumonia.', 'Prevenção', 'Shield'),
('Atenção ao Açúcar', 'Reduzir doces e carboidratos simples ajuda a manter a energia estável durante o dia.', 'Nutrição', 'Apple'),
('Uso de Óculos', 'Sempre use seus óculos ao organizar seus remédios para garantir a dosagem certa.', 'Segurança', 'Info'),
('Ventilação em Casa', 'Abra as janelas diariamente para renovar o ar e evitar problemas respiratórios.', 'Ambiente', 'Home'),
('Alongamento Matinal', 'Alongar os braços e pernas ao acordar melhora a flexibilidade e evita dores musculares.', 'Físico', 'Activity'),
('Amizades e Saúde', 'Manter contato com amigos ajuda a prevenir a depressão e o isolamento social.', 'Social', 'Users'),
('Cuidado com Escadas', 'Use sempre o corrimão ao subir ou descer escadas, mesmo que se sinta seguro.', 'Segurança', 'Shield'),
('Higiene Bucal', 'A saúde começa pela boca. Escove os dentes após as refeições e use fio dental.', 'Higiene', 'Smile'),
('Consulta de Retorno', 'Marque suas consultas de retorno assim que sair do consultório para não perder o acompanhamento.', 'Gestão', 'Calendar'),
('Frutas e Fibras', 'Consuma frutas com casca ou bagaço sempre que possível para melhorar a digestão.', 'Nutrição', 'Apple'),
('O Poder do Abraço', 'Abraçar quem amamos libera ocitocina, o hormônio do bem-estar e da segurança.', 'Amor', 'Heart'),
('Controle da Pressão', 'Meça sua pressão regularmente e anote os valores para mostrar ao seu médico.', 'Monitoramento', 'Clipboard'),
('Sopa de Legumes', 'Uma sopa leve no jantar é fácil de digerir e ajuda no sono tranquilo.', 'Alimentação', 'Apple'),
('Evite Frituras', 'Opte por alimentos grelhados ou cozidos para manter o colesterol em níveis saudáveis.', 'Nutrição', 'Droplet'),
('Sol no Lado Certo', 'Ao dirigir ou sentar perto da janela, proteja o lado do corpo exposto ao sol.', 'Cuidado', 'Sun'),
('Limpeza do Celular', 'Limpe a tela do seu celular com álcool isopropílico para evitar o acúmulo de bactérias.', 'Higiene', 'Info'),
('Apoio de Braço', 'Use cadeiras com braços para facilitar o ato de levantar e sentar com segurança.', 'Segurança', 'Shield'),
('Música e Memória', 'Ouvir músicas da sua juventude ajuda a exercitar a memória e melhora o humor.', 'Mente', 'Heart'),
('Chá de Gengibre', 'O gengibre ajuda na digestão e pode aliviar náuseas, mas use com moderação.', 'Dicas', 'Apple'),
('Evite Roupas Apertadas', 'Roupas leves facilitam a circulação sanguínea e o movimento do corpo.', 'Bem-estar', 'User'),
('Cuidado com a Audição', 'Se estiver ouvindo TV muito alto, pode ser hora de uma consulta com o otorrinolaringologista.', 'Saúde', 'Info'),
('Passeio no Parque', 'O contato com a natureza reduz o estresse e revigora as energias.', 'Bem-estar', 'Smile'),
('Vitaminas Naturais', 'Priorize obter vitaminas de frutas e vegetais frescos antes de recorrer a suplementos.', 'Nutrição', 'Apple'),
('Não Fumar', 'Parar de fumar em qualquer idade traz benefícios imediatos para o coração e pulmões.', 'Saúde', 'AlertTriangle'),
('Moderação no Álcool', 'O álcool pode interagir perigosamente com muitos medicamentos. Pergunte ao seu médico.', 'Segurança', 'AlertTriangle'),
('Leitura Diária', 'Ler um pouco todos os dias mantém o cérebro ativo e expande o conhecimento.', 'Mente', 'BookOpen'),
('Escrita à Mão', 'Escrever bilhetes ou cartas ajuda a manter a coordenação motora fina.', 'Atividade', 'Edit3'),
('Uso de Corrimão', 'Sempre utilize o corrimão em áreas públicas para evitar desequilíbrios inesperados.', 'Segurança', 'Shield'),
('Calçados em Casa', 'Evite andar descalço ou apenas de meias. Use chinelos com solado antiderrapante.', 'Segurança', 'Home'),
('Organização de Gavetas', 'Manter objetos de uso diário em locais de fácil alcance evita o esforço excessivo.', 'Conforto', 'Home'),
('Lanche Saudável', 'Tenha sempre uma fruta ou castanhas para pequenos lanches entre as refeições.', 'Nutrição', 'Apple'),
('Cuidado com Animais', 'Cuidado ao caminhar perto de pets para não tropeçar neles, especialmente à noite.', 'Segurança', 'Smile'),
('Visitas Médicas', 'Leve sempre uma lista de todos os remédios que toma para cada consulta que for.', 'Organização', 'Clipboard'),
('Paciência Consigo', 'Alguns dias são mais lentos. Respeite o ritmo do seu corpo sem se cobrar tanto.', 'Mente', 'Heart'),
('Respiração Profunda', 'Pratique respirar fundo 5 vezes seguidas quando se sentir ansioso ou cansado.', 'Bem-estar', 'Activity'),
('Prevenção de Queimaduras', 'Cuidado ao manusear panelas quentes. Use sempre luvas térmicas de boa qualidade.', 'Segurança', 'Home'),
('Check-up Dentário', 'A saúde da gengiva está ligada à saúde do coração. Não esqueça do dentista.', 'Higiene', 'Smile'),
('Cuidado com o Frio', 'Mantenha-se bem agasalhado em dias frios para evitar dores nas articulações.', 'Cuidado', 'Heart'),
('Sol da Manhã', 'O sol antes das 10h é o melhor para a saúde e para começar o dia bem.', 'Hábito', 'Sun'),
('Importância do Cálcio', 'Leite, queijos e iogurtes ajudam a manter os ossos fortes e prevenir fraturas.', 'Nutrição', 'Apple'),
('Evite Longas Viagens', 'Se for viajar por muito tempo, faça paradas para alongar e caminhar um pouco.', 'Circulação', 'Activity'),
('Atenção a Tonturas', 'Se sentir tontura ao levantar, espere um pouco sentado antes de ficar em pé.', 'Segurança', 'AlertTriangle'),
('Higiene do Sono', 'Evite telas de celular ou TV pelo menos 30 minutos antes de dormir.', 'Sono', 'Moon'),
('Amor Próprio', 'Tire um tempo todos os dias para fazer algo que você realmente gosta.', 'Bem-estar', 'Heart'),
('Cuidado com Produtos', 'Mantenha produtos de limpeza longe de onde guarda seus medicamentos.', 'Segurança', 'AlertTriangle'),
('Uso de Bengala', 'Se o médico recomendou o uso de apoio, use-o com orgulho. Ele é seu aliado.', 'Segurança', 'User'),
('Proteção de Pele', 'Use hidratante após o banho para evitar que a pele fique seca e com coceiras.', 'Higiene', 'Droplet'),
('Evite Pesos', 'Não carregue sacolas muito pesadas. Divida o peso entre os dois braços.', 'Físico', 'Activity'),
('Cuidado com Tapetes Novos', 'Sempre verifique se tapetes novos estão bem fixos ao chão antes de pisar.', 'Segurança', 'Shield'),
('Importância do Magnésio', 'Alimentos como castanhas e espinafre são ricos em magnésio, bom para os músculos.', 'Nutrição', 'Apple'),
('Conversa com Vizinhos', 'Manter uma boa relação com vizinhos cria uma rede de apoio importante.', 'Social', 'Users'),
('Evite Cafeína à Noite', 'Café e chás pretos podem tirar o sono se tomados após as 17 horas.', 'Sono', 'Coffee'),
('Cuidado com Degraus', 'Pinte a borda de degraus com cores contrastantes para visualizá-los melhor.', 'Segurança', 'Home'),
('Hábito de Sorrir', 'Sorrir para si no espelho pela manhã ajuda a começar o dia com mais leveza.', 'Humor', 'Smile'),
('Organização de Chaves', 'Tenha um local fixo para as chaves para evitar o estresse de procurá-las.', 'Hábito', 'Home'),
('Uso de Filtro Solar', 'Mesmo em dias nublados, os raios UV atingem a pele. Proteja-se sempre.', 'Cuidado', 'Sun'),
('Cuidado com Medicamentos', 'Nunca compartilhe seus remédios com amigos, mesmo que os sintomas sejam iguais.', 'Segurança', 'AlertTriangle'),
('Importância das Fibras', 'Fibras ajudam no funcionamento do intestino e dão saciedade.', 'Nutrição', 'Apple'),
('Cuidado com Calçadas', 'Ao caminhar na rua, prefira calçadas planas e evite buracos ou raízes de árvores.', 'Segurança', 'Activity'),
('Agradecimento', 'Termine o dia pensando em three coisas boas que aconteceram hoje.', 'Mente', 'Heart'),
('Boas Energias', 'Mantenha plantas ou flores coloridas em casa para alegrar o ambiente.', 'Bem-estar', 'Smile'),
('Cuidado com Escadas', 'Use sempre o corrimão ao subir ou descer escadas, mesmo que se sinta seguro.', 'Segurança', 'Shield'),
('Higiene Bucal', 'A saúde começa pela boca. Escove os dentes após as refeições e use fio dental.', 'Higiene', 'Smile'),
('Consulta de Retorno', 'Marque suas consultas de retorno assim que sair do consultório para não perder o acompanhamento.', 'Gestão', 'Calendar'),
('Frutas e Fibras', 'Consuma frutas com casca ou bagaço sempre que possível para melhorar a digestão.', 'Nutrição', 'Apple'),
('O Poder do Abraço', 'Abraçar quem amamos libera ocitocina, o hormônio do bem-estar e da segurança.', 'Amor', 'Heart'),
('Controle da Pressão', 'Meça sua pressão regularmente e anote os valores para mostrar ao seu médico.', 'Monitoramento', 'Clipboard'),
('Sopa de Legumes', 'Uma sopa leve no jantar é fácil de digerir e ajuda no sono tranquilo.', 'Alimentação', 'Apple'),
('Evite Frituras', 'Opte por alimentos grelhados ou cozidos para manter o colesterol em níveis saudáveis.', 'Nutrição', 'Droplet'),
('Sol no Lado Certo', 'Ao dirigir ou sentar perto da janela, proteja o lado do corpo exposto ao sol.', 'Cuidado', 'Sun'),
('Limpeza do Celular', 'Limpe a tela do seu celular com álcool isopropílico para evitar o acúmulo de bactérias.', 'Higiene', 'Info'),
('Apoio de Braço', 'Use cadeiras com braços para facilitar o ato de levantar e sentar com segurança.', 'Segurança', 'Shield'),
('Música e Memória', 'Ouvir músicas da sua juventude ajuda a exercitar a memória e melhora o humor.', 'Mente', 'Heart'),
('Chá de Gengibre', 'O gengibre ajuda na digestão e pode aliviar náuseas, mas use com moderação.', 'Dicas', 'Apple'),
('Evite Roupas Apertadas', 'Roupas leves facilitam a circulação sanguínea e o movimento do corpo.', 'Bem-estar', 'User'),
('Cuidado com a Audição', 'Se estiver ouvindo TV muito alto, pode ser hora de uma consulta com o otorrinolaringologista.', 'Saúde', 'Info'),
('Passeio no Parque', 'O contato com a natureza reduz o estresse e revigora as energias.', 'Bem-estar', 'Smile'),
('Vitaminas Naturais', 'Priorize obter vitaminas de frutas e vegetais frescos antes de recorrer a suplementos.', 'Nutrição', 'Apple'),
('Não Fumar', 'Parar de fumar em qualquer idade traz benefícios imediatos para o coração e pulmões.', 'Saúde', 'AlertTriangle'),
('Moderação no Álcool', 'O álcool pode interagir perigosamente com muitos medicamentos. Pergunte ao seu médico.', 'Segurança', 'AlertTriangle'),
('Leitura Diária', 'Ler um pouco todos os dias mantém o cérebro ativo e expande o conhecimento.', 'Mente', 'BookOpen'),
('Escrita à Mão', 'Escrever bilhetes ou cartas ajuda a manter a coordenação motora fina.', 'Atividade', 'Edit3'),
('Uso de Corrimão', 'Sempre utilize o corrimão em áreas públicas para evitar desequilíbrios inesperados.', 'Segurança', 'Shield'),
('Calçados em Casa', 'Evite andar descalço ou apenas de meias. Use chinelos com solado antiderrapante.', 'Segurança', 'Home'),
('Organização de Gavetas', 'Manter objetos de uso diário em locais de fácil alcance evita o esforço excessivo.', 'Conforto', 'Home'),
('Lanche Saudável', 'Tenha sempre uma fruta ou castanhas para pequenos lanches entre as refeições.', 'Nutrição', 'Apple'),
('Cuidado com Animais', 'Cuidado ao caminhar perto de pets para não tropeçar neles, especialmente à noite.', 'Segurança', 'Smile'),
('Visitas Médicas', 'Leve sempre uma lista de todos os remédios que toma para cada consulta que for.', 'Organização', 'Clipboard'),
('Paciência Consigo', 'Alguns dias são mais lentos. Respeite o ritmo do seu corpo sem se cobrar tanto.', 'Mente', 'Heart'),
('Respiração Profunda', 'Pratique respirar fundo 5 vezes seguidas quando se sentir ansioso ou cansado.', 'Bem-estar', 'Activity'),
('Prevenção de Queimaduras', 'Cuidado ao manusear panelas quentes. Use sempre luvas térmicas de boa qualidade.', 'Segurança', 'Home'),
('Check-up Dentário', 'A saúde da gengiva está ligada à saúde do coração. Não esqueça do dentista.', 'Higiene', 'Smile'),
('Cuidado com o Frio', 'Mantenha-se bem agasalhado em dias frios para evitar dores nas articulações.', 'Cuidado', 'Heart'),
('Sol da Manhã', 'O sol antes das 10h é o melhor para a saúde e para começar o dia bem.', 'Hábito', 'Sun'),
('Importância do Cálcio', 'Leite, queijos e iogurtes ajudam a manter os ossos fortes e prevenir fraturas.', 'Nutrição', 'Apple'),
('Evite Longas Viagens', 'Se for viajar por muito tempo, faça paradas para alongar e caminhar um pouco.', 'Circulação', 'Activity'),
('Atenção a Tonturas', 'Se sentir tontura ao levantar, espere um pouco sentado antes de ficar em pé.', 'Segurança', 'AlertTriangle'),
('Higiene do Sono', 'Evite telas de celular ou TV pelo menos 30 minutos antes de dormir.', 'Sono', 'Moon'),
('Amor Próprio', 'Tire um tempo todos os dias para fazer algo que você realmente gosta.', 'Bem-estar', 'Heart'),
('Cuidado com Produtos', 'Mantenha produtos de limpeza longe de onde guarda seus medicamentos.', 'Segurança', 'AlertTriangle'),
('Uso de Bengala', 'Se o médico recomendou o uso de apoio, use-o com orgulho. Ele é seu aliado.', 'Segurança', 'User'),
('Proteção de Pele', 'Use hidratante após o banho para evitar que a pele fique seca e com coceiras.', 'Higiene', 'Droplet'),
('Evite Pesos', 'Não carregue sacolas muito pesadas. Divida o peso entre os dois braços.', 'Físico', 'Activity'),
('Cuidado com Tapetes Novos', 'Sempre verifique se tapetes novos estão bem fixos ao chão antes de pisar.', 'Segurança', 'Shield'),
('Importância do Magnésio', 'Alimentos como castanhas e espinafre são ricos em magnésio, bom para os músculos.', 'Nutrição', 'Apple'),
('Conversa com Vizinhos', 'Manter uma boa relação com vizinhos cria uma rede de apoio importante.', 'Social', 'Users'),
('Evite Cafeína à Noite', 'Café e chás pretos podem tirar o sono se tomados após as 17 horas.', 'Sono', 'Coffee'),
('Cuidado com Degraus', 'Pinte a borda de degraus com cores contrastantes para visualizá-los melhor.', 'Segurança', 'Home'),
('Hábito de Sorrir', 'Sorrir para si no espelho pela manhã ajuda a começar o dia com mais leveza.', 'Humor', 'Smile'),
('Organização de Chaves', 'Tenha um local fixo para as chaves para evitar o estresse de procurá-las.', 'Hábito', 'Home'),
('Uso de Filtro Solar', 'Mesmo em dias nublados, os raios UV atingem a pele. Proteja-se sempre.', 'Cuidado', 'Sun'),
('Cuidado com Medicamentos', 'Nunca compartilhe seus remédios com amigos, mesmo que os sintomas sejam iguais.', 'Segurança', 'AlertTriangle'),
('Importância das Fibras', 'Fibras ajudam no funcionamento do intestino e dão saciedade.', 'Nutrição', 'Apple'),
('Cuidado com Calçadas', 'Ao caminhar na rua, prefira calçadas planas e evite buracos ou raízes de árvores.', 'Segurança', 'Activity'),
('Agradecimento Especial', 'Ligue para alguém que você gosta apenas para dar "oi" e agradecer pela amizade.', 'Social', 'Heart'),
('Atividade com as Mãos', 'Fazer tricô, pintura ou marcenaria ajuda na concentração e reduz a ansiedade.', 'Mente', 'Smile'),
('Cuidado com o Sol da Tarde', 'O sol das 11h às 16h é o mais forte. Evite sair se puder.', 'Prevenção', 'Sun'),
('Hidratação dos Olhos', 'Se sentir os olhos secos, use colírio lubrificante indicado pelo seu médico.', 'Cuidado', 'Droplet'),
('Postura no Sofá', 'Use almofadas para apoiar a lombar enquanto descansa ou assiste TV.', 'Conforto', 'User'),
('Importância do Ferro', 'Feijão e carne vermelha magra ajudam a prevenir a anemia e dão energia.', 'Nutrição', 'Apple'),
('Meditação Simples', 'Feche os olhos por 2 minutos e preste atenção apenas na sua respiração.', 'Mente', 'Moon'),
('Cuidado com Objetos no Chão', 'Mantenha fios e brinquedos fora dos caminhos de passagem da casa.', 'Segurança', 'Shield'),
('Rotina de Banho', 'Use tapete emborrachado dentro do box e fora dele para garantir segurança máxima.', 'Higiene', 'Droplet'),
('Vitamina C no Inverno', 'Laranja, limão e acerola fortalecem sua imunidade contra resfriados.', 'Nutrição', 'Apple'),
('Troca de Filtros', 'Limpe o filtro do ar-condicionado mensalmente para garantir ar puro em casa.', 'Ambiente', 'Home'),
('Cuidado com o Pescoço', 'Não durma com travesseiros muito altos ou muito baixos para evitar dores.', 'Bem-estar', 'Moon'),
('Exercite o Riso', 'Assista a um filme de comédia ou leia algo engraçado todos os dias.', 'Humor', 'Smile'),
('Consumo de Iogurte', 'O iogurte natural ajuda a manter a flora intestinal equilibrada.', 'Nutrição', 'Apple'),
('Cuidado com Escadas de Mão', 'Evite subir em escadinhas ou bancos para alcançar o alto dos armários.', 'Segurança', 'AlertTriangle'),
('Frequência Cardíaca', 'Saiba como medir seu pulso. É uma informação útil para passar ao médico.', 'Monitoramento', 'Activity'),
('Descanso dos Olhos', 'Se ler por muito tempo, olhe para algo longe por alguns segundos para descansar.', 'Dicas', 'Info'),
('Importância do Sol no Inverno', 'Mesmo no frio, o sol é essencial para a produção de serotonina.', 'Mente', 'Sun'),
('Cuidado com a Pele Secos', 'Beba água extra se notar que sua pele está descamando mais que o normal.', 'Higiene', 'Droplet'),
('Organização de Contas', 'Mantenha um calendário visual de pagamentos para não se preocupar com datas.', 'Gestão', 'Calendar'),
('Uso de Corrimão no Ônibus', 'Ao usar transporte público, segure firme nos apoios antes de o veículo sair.', 'Segurança', 'Shield'),
('Importância das Proteínas', 'Comer ovo ou frango ajuda a manter a massa muscular em dia.', 'Nutrição', 'Apple'),
('Cuidado com o Álcool em Gel', 'Use álcool em gel na rua, mas prefira água e sabão sempre que possível.', 'Higiene', 'Info'),
('Postura na Cozinha', 'Sente-se para descascar alimentos ou preparar receitas longas.', 'Conforto', 'Home'),
('Momento de Estudo', 'Aprender uma palavra nova por dia ajuda a manter o cérebro jovem.', 'Mente', 'BookOpen'),
('Cuidado com Tapetes de Banheiro', 'Certifique-se de que o tapete de saída do banho esteja sempre seco.', 'Segurança', 'Droplet'),
('Vitaminas Naturais Diversas', 'As cores no prato indicam nutrientes diferentes. Tente variar as cores sempre.', 'Nutrição', 'Apple'),
('Cuidado com o Verão Forte', 'Use roupas de algodão ou tecidos que deixam a pele respirar nos dias quentes.', 'Bem-estar', 'Sun'),
('Importância do Zinco em Sementes', 'Semente de abóbora e castanhas são ótimas fontes de zinco para a imunidade.', 'Nutrição', 'Apple'),
('Cuidado com Escadas de Caracol Instáveis', 'Se puder, evite escadas em caracol, elas são mais instáveis para o equilíbrio.', 'Segurança', 'AlertTriangle'),
('Socialização Digital com Netos', 'Aprenda a fazer chamadas de vídeo para ver os netos e amigos com frequência.', 'Mente', 'Smile'),
('Cuidado com Alimentos Gelados nos Dentes', 'Alimentos muito gelados podem causar sensibilidade nos dentes e garganta.', 'Dicas', 'Apple'),
('Importância do Potássio nas Bananas', 'A banana ajuda a prevenir cãibras musculares irritantes à noite.', 'Nutrição', 'Apple'),
('Cuidado com a Memória e Jogos', 'Fazer palavras cruzadas ou sudoku é excelente para exercitar o raciocínio.', 'Mente', 'Edit3'),
('Higiene das Unhas Curtas', 'Mantenha as unhas cortadas e limpas para evitar o acúmulo de sujeira.', 'Higiene', 'Info'),
('Cuidado com a Pressão Baixa ao Levantar', 'Se sentir fraqueza ao levantar rápido, beba um copo de água imediamente.', 'Saúde', 'Droplet'),
('Importância da Vitamina B12 no Idoso', 'Consulte seu médico sobre a B12, essencial para o sistema nervoso no idoso.', 'Nutrição', 'Clipboard'),
('Cuidado com o Calor Excessivo em Casa', 'Use ventiladores ou ar-condicionado para manter o ambiente fresco no verão.', 'Conforto', 'Home'),
('Hábito de Alongar os Pés ao Acordar', 'Gire os pés para os dois lados ao acordar para ativar a circulação.', 'Circulação', 'Activity'),
('Cuidado com Caminhadas no Escuro à Noite', 'Sempre leve uma lanterna ou use a do celular se for caminhar à noite.', 'Segurança', 'Sun'),
('Importância do Silêncio Mental', 'Tire 10 minutos de silêncio absoluto para acalmar a mente e reduzir o ruído.', 'Bem-estar', 'Moon'),
('Cuidado com Calçados Estreitos e Calos', 'Sapatos apertados podem causar calos e feridas difíceis de cicatrizar.', 'Higiene', 'User'),
('Importância das Leguminosas no Almoço', 'Grão-de-bico e lentilha são ótimos substitutos para carnes em alguns dias.', 'Nutrição', 'Apple'),
('Cuidado com Janelas Altas e Bancos', 'Peça ajuda para limpar janelas ou trocar cortinas. Evite subir em bancos.', 'Segurança', 'AlertTriangle'),
('Aproveite o Hoje Sempre', 'Cada dia é uma nova oportunidade de ser feliz. Foque no presente!', 'Vida', 'Heart'),
('Cuidado com Piso Molhado', 'Mantenha um pano seco por perto na cozinha para limpar respingos de água imediatamente.', 'Segurança', 'Droplet'),
('Importância do Magnésio', 'O magnésio ajuda a relaxar os músculos e melhora a qualidade do sono.', 'Nutrição', 'Moon'),
('Cuidado com Escadas sem Luz', 'Instale luzes com sensor de movimento no corredor e perto de escadas.', 'Segurança', 'Sun'),
('Socialização com Amigos', 'Marcar um café semanal com amigos ajuda a manter o vínculo social ativo.', 'Mente', 'Users'),
('Hábito de Ler Rótulos', 'Verifique a quantidade de sódio e açúcar nos alimentos industrializados.', 'Nutrição', 'Info'),
('Cuidado com Ventos Fortes', 'Mantenha as janelas bem presas em dias de vento para evitar batidas bruscas.', 'Segurança', 'Home'),
('Importância do Descanso', 'Tire um cochilo curto de 20 minutos após o almoço para renovar as energias.', 'Bem-estar', 'Moon'),
('Cuidado com a Pele no Verão', 'Use hidratantes refrescantes e beba água de coco para se manter hidratado.', 'Higiene', 'Droplet'),
('Hábito de Planejar o Dia', 'Anote as 3 tarefas principais que deseja realizar para não se sobrecarregar.', 'Gestão', 'Calendar'),
('Cuidado com Degraus de Calçada', 'Sempre olhe para o chão ao caminhar em locais desconhecidos.', 'Segurança', 'AlertTriangle'),
('Importância das Proteínas Verdes', 'Ervilhas e brócolis são ótimas fontes de proteína vegetal e ferro.', 'Nutrição', 'Apple'),
('Cuidado com o Uso do Celular', 'Não caminhe olhando para o celular para evitar tropeços e colisões.', 'Segurança', 'Info'),
('Hábito de Ouvir Podcasts', 'Ouvir histórias ou notícias ajuda a manter o cérebro engajado e curioso.', 'Mente', 'BookOpen'),
('Cuidado com Tapetes de Quarto', 'Remova tapetes do caminho entre a cama e o banheiro para evitar quedas noturnas.', 'Segurança', 'Shield'),
('Importância de Sorrir', 'O ato de sorrir diminui a produção de cortisol, o hormônio do estresse.', 'Bem-estar', 'Smile'),
('Cuidado com a Visão Noturna', 'Se precisar levantar à noite, acenda uma luz fraca para enxergar o caminho.', 'Segurança', 'Sun'),
('Hábito de Alongar os Braços', 'Estique os braços acima da cabeça por 30 segundos várias vezes ao dia.', 'Físico', 'Activity'),
('Cuidado com Alimentos Muito Quentes', 'Espere a comida esfriar um pouco para evitar queimaduras na boca e garganta.', 'Dicas', 'Apple'),
('Importância da Vitamina A', 'Cenoura e abóbora são excelentes para a saúde dos seus olhos e da pele.', 'Nutrição', 'Apple'),
('Cuidado com Medicamentos Vencidos', 'Nunca use remédios fora do prazo de validade, eles podem ser ineficazes ou tóxicos.', 'Segurança', 'AlertTriangle'),
('Hábito de Conversar com Vizinhos', 'Um simples "bom dia" cria um ambiente mais seguro e acolhedor na vizinhança.', 'Social', 'Users'),
('Cuidado com o Desequilíbrio', 'Ao vestir calças ou meias, faça-o sentado para garantir que não vai cair.', 'Segurança', 'Shield'),
('Importância do Selênio', 'Uma castanha-do-pará por dia já fornece todo o selênio que seu corpo precisa.', 'Nutrição', 'Apple'),
('Cuidado com Escadas de Piscina', 'Sempre use o corrimão e desça com cuidado ao entrar ou sair da água.', 'Segurança', 'Droplet'),
('Hábito de Registrar Sintomas', 'Use cores diferentes para marcar a intensidade de dores no seu diário.', 'Monitoramento', 'Edit3'),
('Cuidado com a Postura no Computador', 'Mantenha a tela na altura dos olhos e os pés bem apoiados no chão.', 'Ergonomia', 'User'),
('Importância do Chá de Erva-Doce', 'Ajuda a reduzir gases e melhora a digestão após refeições pesadas.', 'Dicas', 'Apple'),
('Cuidado com Tapetes de Cozinha', 'Prefira tapetes que sejam emborrachados em toda a sua extensão inferior.', 'Segurança', 'Shield'),
('Hábito de Ver Fotos Antigas', 'Recordar bons momentos ajuda a manter a conexão emocional e a memória.', 'Mente', 'Heart'),
('Cuidado com o Uso de Escadas Caracol', 'Suba um degrau por vez e mantenha uma mão sempre livre para o corrimão.', 'Segurança', 'Shield'),
('Importância da Vitamina E', 'Azeite de oliva e amêndoas protegem as células contra o envelhecimento precoce.', 'Nutrição', 'Apple'),
('Cuidado com o Chão Encerado', 'Piso muito brilhante pode estar escorregadio. Caminhe com passos curtos.', 'Segurança', 'AlertTriangle'),
('Hábito de Alongar o Pescoço', 'Incline a cabeça levemente para os lados para aliviar a tensão dos ombros.', 'Bem-estar', 'Activity'),
('Cuidado com o Sol de Inverno', 'Mesmo no frio, os raios UV podem queimar a pele. Não esqueça o protetor.', 'Cuidado', 'Sun'),
('Importância do Cálcio em Vegetais', 'Couve e brócolis também são ótimas fontes de cálcio para quem não toma leite.', 'Nutrição', 'Apple'),
('Cuidado com as Unhas dos Pés', 'Corte-as em linha reta para evitar que encravem e causem dor ao caminhar.', 'Higiene', 'Info'),
('Hábito de Beber Água de Coco', 'Excelente repositor de minerais natural para dias quentes ou após exercícios.', 'Nutrição', 'Droplet'),
('Cuidado com Correntes de Ar', 'Mantenha as portas fechadas ou use pesos de porta para evitar batidas.', 'Segurança', 'Home'),
('Importância da Gratidão', 'Anotar algo pelo qual você é grato melhora significativamente seu humor.', 'Mente', 'Heart'),
('Cuidado com Calçadas Irregulares', 'Se houver buracos, caminhe devagar ou peça apoio ao seu acompanhante.', 'Segurança', 'AlertTriangle'),
('Hábito de Ver o Pôr do Sol', 'Apreciar a beleza da natureza traz paz e ajuda a encerrar o dia bem.', 'Bem-estar', 'Sun'),
('Cuidado com o Peso de Sacolas', 'Use carrinhos de compra para não sobrecarregar sua coluna e articulações.', 'Segurança', 'Shield'),
('Importância da Vitamina K', 'Espinafre e folhas verdes ajudam na coagulação do sangue e saúde óssea.', 'Nutrição', 'Apple'),
('Cuidado com o Uso de Escadas de Mão', 'Peça para alguém segurar a escada para você ou prefira que façam o serviço.', 'Segurança', 'AlertTriangle'),
('Hábito de Praticar Hobbies', 'Pintura, bordado ou coleção de selos mantêm a mente focada e relaxada.', 'Mente', 'Smile'),
('Cuidado com o Frio nos Pés', 'Use meias confortáveis para dormir e manter a circulação ativa durante a noite.', 'Bem-estar', 'Heart'),
('Importância do Fósforo', 'Presente em ovos e peixes, é essencial para manter seus dentes e ossos fortes.', 'Nutrição', 'Apple'),
('Cuidado com Banheiros Públicos', 'Sempre verifique se há barras de apoio disponíveis antes de usar.', 'Segurança', 'Shield'),
('Hábito de Ouvir Música Suave', 'Música clássica ou instrumental ajuda a baixar a pressão e relaxar.', 'Bem-estar', 'Moon'),
('Cuidado com a Exposição ao Vento', 'Proteja seus ouvidos em dias de vento forte para evitar dores e infecções.', 'Saúde', 'Info'),
('Importância do Ômega-3', 'Ajudar a manter o coração saudável e as funções cerebrais em dia.', 'Nutrição', 'Heart'),
('Cuidado com a Pele Seca no Inverno', 'Use óleos de banho ou hidratantes potentes para evitar rachaduras.', 'Higiene', 'Droplet'),
('Hábito de Meditar', 'Comece com apenas 1 minuto de foco total na sua respiração matinal.', 'Mente', 'Moon'),
('Cuidado com Produtos de Limpeza Fortes', 'Mantenha as janelas abertas ao usar água sanitária ou outros químicos.', 'Segurança', 'Home'),
('Importância do Contato com a Terra', 'Cuidar de um jardim ou mesmo de vasos de plantas renova as energias.', 'Bem-estar', 'Smile'),
('Cuidado com o Uso de Chinelos Velhos', 'Chinelos com solado gasto perdem a aderência e podem causar quedas.', 'Segurança', 'AlertTriangle'),
('Hábito de Fazer Alongamento nos Dedos', 'Abra e feche as mãos repetidamente para manter a agilidade das articulações.', 'Atividade', 'Activity'),
('Cuidado com a Pressão da Água', 'Verifique se a temperatura do chuveiro está agradável antes de entrar.', 'Conforto', 'Droplet'),
('Importância de Beber Chá Verde', 'Rico em antioxidantes, ajuda a proteger as células do corpo.', 'Nutrição', 'Apple'),
('Cuidado com Degraus Curtos', 'Eles são os mais perigosos para tropeços. Redobre a atenção neles.', 'Segurança', 'AlertTriangle'),
('Hábito de Planejar Refeições', 'Ter o cardápio da semana ajuda a comer de forma equilibrada e sem pressa.', 'Gestão', 'Calendar'),
('Cuidado com a Limpeza de Óculos', 'Lentes sujas cansam a visão e podem causar dores de cabeça inúteis.', 'Higiene', 'Info'),
('Importância do Ar Puro', 'Sempre que possível, vá a um local com muitas árvores para respirar melhor.', 'Bem-estar', 'Sun'),
('Cuidado com o Peso de Livros', 'Prefira ler em locais onde possa apoiar o livro em uma mesa ou almofada.', 'Conforto', 'BookOpen'),
('Hábito de Anotar Recados', 'Tenha um bloco de notas perto do telefone para não esquecer informações.', 'Gestão', 'Edit3'),
('Cuidado com o Uso de Tapetes em Escadas', 'Nunca coloque tapetes soltos em degraus de escada, é risco alto de queda.', 'Segurança', 'Shield'),
('Importância da Vitamina D', 'Tente pegar um pouco de sol nos braços e pernas diariamente se possível.', 'Saúde', 'Sun'),
('Cuidado com o Frio Intenso', 'Use cachecol para proteger a garganta e evitar gripes em dias gelados.', 'Prevenção', 'Heart'),
('Hábito de Visitar Museus', 'Atividade cultural estimula a curiosidade e o aprendizado constante.', 'Mente', 'BookOpen'),
('Cuidado com o Peso de Maletas', 'Use mochilas de duas alças para distribuir o peso igualmente nos ombros.', 'Segurança', 'Shield'),
('Importância das Fibras em Grãos', 'Arroz e pão integral ajudam a manter a energia por mais tempo.', 'Nutrição', 'Apple'),
('Cuidado com a Umidade em Casa', 'Use desumidificadores ou abra os armários para evitar o mofo.', 'Ambiente', 'Home'),
('Hábito de Cumprimentar Pessoas', 'Ser gentil com quem passa por você melhora o seu próprio dia.', 'Social', 'Smile'),
('Cuidado com o Uso de Ferramentas', 'Ao usar martelos ou chaves, faça-o com boa iluminação e sem pressa.', 'Segurança', 'Shield'),
('Importância da Mastigação', 'Mastigar devagar ajuda o estômago a processar os alimentos melhor.', 'Dicas', 'Apple'),
('Cuidado com a Temperatura da Água de Beber', 'Água em temperatura ambiente é muitas vezes mais confortável pro estômago.', 'Conforto', 'Droplet'),
('Hábito de Olhar no Horizonte', 'Isso ajuda a relaxar os músculos dos olhos após ler por muito tempo.', 'Higiene', 'Sun'),
('Cuidado com o Uso de Salto Alto', 'Mesmo saltos baixos podem afetar o equilíbrio. Prefira sapatos planos.', 'Segurança', 'User'),
('Importância das Ervas Aromáticas', 'Use alecrim, manjericão e orégano para dar sabor sem precisar de muito sal.', 'Nutrição', 'Apple'),
('Cuidado com o Brilho das Telas', 'Diminua a luminosidade do celular à noite para não afetar seu sono.', 'Higiene', 'Moon'),
('Hábito de Fazer Caminhada de Manhã', 'O ar é mais fresco e a iluminação ajuda a despertar o corpo.', 'Bem-estar', 'Sun'),
('Cuidado com a Postura ao Sentar', 'Mantenha as costas encostadas no fundo da cadeira sempre que possível.', 'Ergonomia', 'User'),
('Importância das Castanhas', 'Um punhado pequeno de nozes ou amêndoas é um lanche saudável e nutritivo.', 'Nutrição', 'Apple'),
('Cuidado com a Validade de Cosméticos', 'Hidratantes e sabonetes velhos podem causar irritações na pele.', 'Higiene', 'Droplet'),
('Hábito de Cultivar uma Planta', 'Cuidar de um ser vivo traz responsabilidade e alegria diária.', 'Bem-estar', 'Smile'),
('Cuidado com a Travessia de Ruas', 'Use sempre a faixa de pedestres e espere o sinal ficar verde para você.', 'Segurança', 'Shield'),
('Importância da Vitamina B6', 'Encontrada no feijão e banana, ajuda no funcionamento do sistema nervoso.', 'Nutrição', 'Apple'),
('Cuidado com a Exposição ao Barulho', 'Evite locais muito barulhentos para proteger sua audição sensitiva.', 'Saúde', 'AlertTriangle'),
('Hábito de Fazer Check-up Anual', 'Consulte seu médico regulamente, mesmo que se sinta muito bem.', 'Prevenção', 'Clipboard'),
('Cuidado com o Calor na Cabeça', 'Use chapéu ou boné ao sair no sol forte para evitar insolação.', 'Segurança', 'Sun'),
('Importância da Vitamina K2', 'Ajuda a direcionar o cálcio para os ossos e dentes, evitando as artérias.', 'Saúde', 'Apple'),
('Cuidado com a Organização de Cabos', 'Use fixadores para prender fios de TV e computador contra a parede.', 'Segurança', 'Shield'),
('Hábito de Beber Suco Natural', 'Dê preferência a sucos feitos na hora e sem adição de açúcar extra.', 'Nutrição', 'Apple'),
('Cuidado com o Caminho do Banheiro', 'Mantenha este trajeto livre de qualquer obstáculo o tempo todo.', 'Segurança', 'Home'),
('Importância das Frutas Vermelhas', 'Morango e amora são ricos em antioxidantes potentes para o cérebro.', 'Nutrição', 'Apple'),
('Cuidado com o Uso de Escadas de Madeira', 'Verifique se os degraus não estão soltos ou rangendo antes de subir.', 'Segurança', 'AlertTriangle'),
('Hábito de Praticar a Generosidade', 'Ajudar alguém de forma simples traz uma sensação de bem-estar incrível.', 'Vida', 'Heart'),
('Cuidado com a Postura ao Dormir', 'Tente manter a coluna alinhada usando travesseiros de apoio adequados.', 'Conforto', 'Moon'),
('Importância do Iodo', 'O sal iodado (com moderação) é essencial para o bom funcionamento da tireoide.', 'Saúde', 'Apple'),
('Cuidado com a Limpeza de Tapetes', 'Sacuda os tapetes fora de casa para não inalar a poeira que se solta.', 'Higiene', 'Info'),
('Hábito de Visitar Parques', 'O verde das árvores ajuda a reduzir o estresse e melhora a oxigenação.', 'Bem-estar', 'Sun'),
('Cuidado com o Uso de Bolsas de Água Quente', 'Sempre verifique se a temperatura não vai queimar sua pele antes de usar.', 'Segurança', 'Droplet'),
('Importância das Gorduras Boas', 'Abacate e azeite são fundamentais para a saúde das suas células.', 'Nutrição', 'Apple'),
('Cuidado com o Excesso de Informação', 'Desligue o noticiário se sentir que está ficando muito ansioso ou triste.', 'Mente', 'AlertTriangle'),
('Hábito de Manter a Casa Arejada', 'Ar renovado evita problemas respiratórios e deixa o ambiente leve.', 'Ambiente', 'Home'),
('Cuidado com o Uso de Óculos de Sol', 'Além de estilo, eles protegem sua retina contra os danos dos raios UV.', 'Saúde', 'Sun'),
('Importância da Resiliência', 'Aceite os imprevistos com calma e busque soluções simples para os problemas.', 'Mente', 'Heart'),
('Cuidado com a Higiene das Mãos na Cozinha', 'Lave-as sempre antes de tocar em frutas ou preparar qualquer lanche.', 'Higiene', 'Info'),
('Hábito de Fazer Atividade Manual', 'Costura, desenho ou culinária estimulam a criatividade e a paciência.', 'Mente', 'Smile'),
('Cuidado com a Postura ao Ler na Cama', 'Use um apoio para as costas e não curve demais o pescoço para baixo.', 'Ergonomia', 'BookOpen'),
('Importância da Vitamina C em Frutas', 'Acerola e goiaba têm ainda mais vitamina C que a própria laranja.', 'Nutrição', 'Apple'),
('Cuidado com o Uso de Lâmpadas Queimadas', 'Troque-as imediatamente para não ficar no escuro e correr riscos.', 'Segurança', 'Sun'),
('Hábito de Ver Programas de Natureza', 'Documentários suaves ajudam a relaxar e aprender coisas novas.', 'Mente', 'BookOpen'),
('Cuidado com o Peso de Compras', 'Se for carregar, divida as sacolas de forma igual entre as duas mãos.', 'Segurança', 'Shield'),
('Importância da Autocompaixão', 'Seja gentil com você mesmo quando cometer um erro ou esquecer algo.', 'Mente', 'Heart'),
('Cuidado com a Limpeza de Tapetes de Banheiro', 'Lave-os semanalmente para evitar o acúmulo de fungos e bactérias.', 'Higiene', 'Droplet'),
('Hábito de Conversar com Familiares', 'Compartilhar seu dia com quem você ama fortalece os laços afetivos.', 'Social', 'Users'),
('Cuidado com o Uso de Utensílios Afiados', 'Mantenha as facas amoladas (exigem menos força) e use-as com atenção.', 'Segurança', 'Shield'),
('Importância de Tomar um Banho Relaxante', 'Água morna à noite ajuda a preparar o corpo para o sono profundo.', 'Bem-estar', 'Moon'),
('Cuidado com a Postura ao Levantar da Cama', 'Vire de lado primeiro, apoie os braços e sente antes de ficar em pé.', 'Segurança', 'User'),
('Hábito de Manter a Fé ou Esperança', 'Ter um propósito ou crença ajuda a enfrentar momentos difíceis com força.', 'Vida', 'Heart'),
('Cuidado com a Exposição ao Calor do Fogão', 'Mantenha certa distância ao cozinhar para não superaquecer o corpo.', 'Segurança', 'Home'),
('Importância da Hidratação na Rua', 'Leve sempre uma garrafinha de água ao sair para caminhar ou fazer compras.', 'Nutrição', 'Droplet'),
('Cuidado com a Postura ao Assistir TV', 'Não fique "largado" no sofá por muitas horas seguidas. Levante e ande.', 'Ergonomia', 'Activity'),
('Hábito de Praticar a Solidariedade', 'Pequenos gestos de ajuda ao próximo trazem um grande retorno emocional.', 'Vida', 'Heart'),
('Cuidado com o Uso de Medicamentos de Terceiros', 'O que serviu para o amigo pode não servir e ser perigoso para você.', 'Segurança', 'AlertTriangle'),
('Importância de Manter a Casa Limpa', 'Um ambiente organizado reflete em uma mente mais calma e focada.', 'Bem-estar', 'Home'),
('Cuidado com a Postura ao Usar o Celular', 'Traga o celular até a altura dos olhos em vez de baixar o pescoço.', 'Ergonomia', 'User'),
('Hábito de Fazer uma Refeição em Família', 'O momento à mesa é precioso para a conexão entre as gerações.', 'Social', 'Users'),
('Cuidado com o Uso de Escadas de Concreto', 'Verifique se não há pontas soltas ou buracos nos degraus antes de subir.', 'Segurança', 'Shield'),
('Importância de Ter um Diário de Gratidão', 'Anotar 3 coisas boas do dia ajuda a reprogramar seu cérebro para o otimismo.', 'Mente', 'Heart'),
('Cuidado com a Postura ao Varrer a Casa', 'Use vassouras de cabo longo para não precisar se curvar excessivamente.', 'Ergonomia', 'Home'),
('Hábito de Ouvir o Canto dos Pássaros', 'Pequenos sons da natureza ajudam a reduzir a pressão arterial.', 'Bem-estar', 'Sun'),
('Cuidado com o Uso de Tapetes em Áreas de Serviço', 'Mantenha o chão sempre seco para evitar que o tapete deslize.', 'Segurança', 'Droplet'),
('Importância da Vitamina B12 Natural', 'Carnes e ovos são as principais fontes. Verifique se precisa suplementar.', 'Saúde', 'Apple'),
('Cuidado com a Postura ao Amarrar Sapatos', 'Sente-se ou use um banquinho para não precisar se curvar demais.', 'Segurança', 'User'),
('Hábito de Abrir as Cortinas de Manhã', 'A luz natural ajuda a regular o seu relógio biológico interno.', 'Bem-estar', 'Sun'),
('Cuidado com o Uso de Produtos com Cheiro Forte', 'Perfumes ou tintas podem causar náuseas ou rinites alérgicas chatas.', 'Saúde', 'Info'),
('Importância de Comer Legumes de Todas as Cores', 'Cada cor oferece um benefício diferente para a sua saúde e imunidade.', 'Nutrição', 'Apple'),
('Cuidado com a Postura ao Lavar Louça', 'Apoie um pé em um pequeno degrau se for ficar muito tempo em pé na pia.', 'Ergonomia', 'Home'),
('Hábito de Praticar a Aceitação', 'Entender que nem tudo está sob nosso controle traz uma paz imensa.', 'Vida', 'Heart'),
('Cuidado com o Uso de Escadas de Ferro', 'Podem estar quentes se pegarem sol. Sempre use o corrimão com atenção.', 'Segurança', 'AlertTriangle'),
('Importância de Reservar Tempo para o Lazer', 'Divertir-se não é perda de tempo, é manutenção da sua saúde mental.', 'Vida', 'Smile'),
('Cuidado com a Postura ao Digitar', 'Mantenha os pulsos retos e os ombros relaxados para evitar tendinites.', 'Ergonomia', 'User'),
('Hábito de Compartilhar Experiências', 'Contar suas histórias para os mais novos é um presente para a família.', 'Social', 'Users'),
('Cuidado com o Uso de Escadas de Alumínio', 'Verifique se as travas de segurança estão bem firmes antes de subir nela.', 'Segurança', 'Shield'),
('Importância de Manter a Mente Ativa Sempre', 'Nunca pare de aprender algo novo, seja um jogo, uma receita ou um idioma.', 'Mente', 'BookOpen'),
('Viva o Presente com Alegria', 'Hoje é o melhor dia para ser feliz. Aproveite cada minuto com gratidão!', 'Vida', 'Heart');
